apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: postgres.deployment.patch.yaml
    target:
      kind: Deployment
      name: postgres
  - path: n8n.deployment.patch.yaml
    target:
      kind: Deployment
      name: n8n
