apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
data:
  N8N_HOST: "n8n.local"
  N8N_PORT: "80"
  N8N_PROTOCOL: "http"
  GENERIC_TIMEZONE: "Europe/Istanbul"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  N8N_DEFAULT_BINARY_DATA_MODE: "filesystem"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  OLLAMA_HOST: "ollama:11434"
